global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'flink-jobmanager'
    metrics_path: /metrics
    static_configs:
      - targets: ['jobmanager:9249']
        labels:
          role: 'jobmanager'
          cluster: 'flink-cluster'

  - job_name: 'flink-taskmanagers'
    metrics_path: /metrics
    static_configs:
      - targets: ['taskmanager-1:9249', 'taskmanager-2:9249']
        labels:
          role: 'taskmanager'
          cluster: 'flink-cluster'

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

